/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_phelps_opensles_JniAudio */

#ifndef _Included_me_phelps_opensles_JniAudio
#define _Included_me_phelps_opensles_JniAudio
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     me_phelps_opensles_JniAudio
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_phelps_opensles_JniAudio_createEngine
        (JNIEnv *, jclass);

/*
 * Class:     me_phelps_opensles_JniAudio
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_phelps_opensles_JniAudio_createRecorder
  (JNIEnv *, jclass);

/*
 * Class:     me_phelps_opensles_JniAudio
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_phelps_opensles_JniAudio_startRecording
        (JNIEnv *, jclass);

/*
 * Class:     me_phelps_opensles_JniAudio
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_phelps_opensles_JniAudio_stopRecording
        (JNIEnv *, jclass);

/*
 * Class:     me_phelps_opensles_JniAudio
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_phelps_opensles_JniAudio_destoryEngine
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
